<a href="https://colab.research.google.com/github/rroxy08/CE888/blob/master/Lab1/lab1_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#LAB1 
#Task 1
import numpy as np

a = np.array([[0,1,],[10,11],[20,21],[30,31]])

print("The array: \n",a)
print("array shape: ",a.shape)
print("array size: ",a.size)
print("array dimensions: ",a.ndim)



The array: 
 [[ 0  1]
 [10 11]
 [20 21]
 [30 31]]
array shape:  (4, 2)
array size:  8
array dimensions:  2


In [0]:
#Task 2  
#Create an array of dimension (1,10) and sort it in ascending and descending order

b = np.array([0,1,2,3,4,5,6,7,8,9])

print("The array:",b)

print("The array in Ascending order:",b[0::])
print("The array in Descending order:",b[::-1])

The array: [0 1 2 3 4 5 6 7 8 9]
The array in Ascending order: [0 1 2 3 4 5 6 7 8 9]
The array in Descending order: [9 8 7 6 5 4 3 2 1 0]


In [0]:
#Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

a = np.array([1,2,3,4,5,6,7,8,9])
k=0
b=[]
for i in range(3):
  temp=[]
  for j in range(3):
    temp.append(a[k])
    k+=1
  b.append(temp)
    
print("1D array: ",a)
print("2D array: ",b)


1D array:  [1 2 3 4 5 6 7 8 9]
2D array:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [0]:
#Stack two arrays of any size horizontally and vertically
a=np.array([0,1,2,3,4,5])
b=np.array([4,5,6,7])

for item in a:
  c.append(item)
print(c)


In [0]:
#Create two array of same size and find commom elements

a=np.array([0,1,2,3,4])
b=np.array([1,6,7,3,0])
common_array=[]

for item in a:
  if item in b:
    common_array.append(item)

print("Common elements are: ",common_array)




Common elements are:  [0, 1, 3]


In [0]:
#Create a 2D array of 5 by 5 and find the min and max values from each row and each column

a=np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45]])

print("The row: \n",a)
# min and max values from each row 
k=1
for row in a:
  for j in range(len(row)):
    min=row[0]
    max=row[0]
    if row[j]<min:
      min=row[j]
    if row[j]>max:
      max=row[j] 
  print("Minimum and Maximum value of row "+str(k)+" are :",min,max)
  k+=1
# min and max values from each column
j=0
k=1
while True:
  if(j==5):
    break
  for i in range(len(a)):
      min=a[0][j]
      max=a[0][j]

      if a[i][j]<min:
        min=a[i][j]
      if a[i][j]>max:
        max=a[i][j]
  j+=1
  
  print("Minimum and Maximum value of column "+str(k)+" are :",min,max)
  k+=1
 

The row: 
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]
Minimum and Maximum value of row 1 are : 1 5
Minimum and Maximum value of row 2 are : 11 15
Minimum and Maximum value of row 3 are : 21 25
Minimum and Maximum value of row 4 are : 31 35
Minimum and Maximum value of row 5 are : 41 45
Minimum and Maximum value of column 1 are : 1 41
Minimum and Maximum value of column 2 are : 2 42
Minimum and Maximum value of column 3 are : 3 43
Minimum and Maximum value of column 4 are : 4 44
Minimum and Maximum value of column 5 are : 5 45


In [0]:
#Create an array of size 100 and compute the mean, median, standard deviation.

#array assignment with random value
a = [100]
for i in range(102):
  a= np.random.randint(100,size=100)


print("The array:",a)
print("Mean value: ",np.mean(a))
print("Median value: ",np.median(a))
print("Standard deviation value: ",np.std(a))


The array: [87 47 55 10 35 58 86 52 17 86 19 83  6 71 98 54  8 26 13 72 29 20 98 83
 65 25 73 41 57 22 57 90  1 35 84 60 14 87 11 28 75 55 35 63 74  0 19 54
 12 11  3 43 60 78 58 15 68 88  5 79  5 43 42 39 75 59 41 10 76 97 61 68
 45 79 22 43 32 92 61 97  5 62 76 99 53 20 68 85 34 22 47 93  5  3 42 57
 68 17 48 56]
Mean value:  49.05
Median value:  53.5
Standard deviation value:  28.753564996361757


In [0]:
#Normalize a 5x5 random matrix

a=np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45]])

print("The row: \n",a)
# min and max values from each row 
normalize_a=[]*len(a)
for row in a:
  t=[]
  for j in range(len(row)):
    min=row[0]
    max=row[0]
    if row[j]<min:
      min=row[j]
    if row[j]>max:
      max=row[j] 
  for j in range(len(row)):
    norm_val= (row[j] - min)/ (max-min)
    t.append(norm_val)
  normalize_a.append(t)

print("Normalized array: ",normalize_a)
  

The row: 
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]
Normalized array:  [[0.0, 0.25, 0.5, 0.75, 1.0], [0.0, 0.25, 0.5, 0.75, 1.0], [0.0, 0.25, 0.5, 0.75, 1.0], [0.0, 0.25, 0.5, 0.75, 1.0], [0.0, 0.25, 0.5, 0.75, 1.0]]


In [0]:
#Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

a=np.array([[[1,1,1],[2,2,2],[3,3,3],[4,4,4]],[[5,5,5],[6,6,6],[7,7,7],[8,8,8]],[[9,9,9],[11,11,11],[12,12,12],[3,3,3]],[[20,20,20],[10,10,10],[30,30,30],[40,40,40]]])
b=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])

c=[]
print(a.shape[0])
for i in range(len(a)):
  t=[]
  k=0
  for j in range(len(a[0])):
    print(a[i][j][k])
    #val=a[i][j][k] * b[i][j]
    k+=1
    t.append(val)
  c.append(t)
print(c)

4
1
2
3


IndexError: ignored