<a href="https://colab.research.google.com/github/rroxy08/CE888/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline
import matplotlib
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import Image
np.set_printoptions(precision = 3)

In [4]:
dframe=pd.read_csv('https://raw.githubusercontent.com/rroxy08/CE888/master/Lab5/jester-data-1.csv', delimiter=',')
dframe


74  -7.82   8.79  -9.66  -8.16  ...  99.22  -5.63  99.23  99.24  99.25
0      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
1       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
2       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
4      100  -6.17  -3.54   0.44  -8.50  ...  -3.35   0.05  -9.08  -5.05  -3.45
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24977  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24978   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24979   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24980   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24982 rows x 101 columns]

In [5]:
arr = dframe.values
print(arr.shape)

(24982, 101)


In [6]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1835282 (1835282,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [8]:
new_arr, idx = replace(arr, 0.1)

print(new_arr)
print(idx)

[[100.     4.08  -0.29 ...  99.    -4.32   1.07]
 [ 49.    99.    99.   ...  99.    99.    99.  ]
 [ 48.    99.     8.35 ...  99.    99.    99.  ]
 ...
 [ 99.    99.    99.   ...  99.    99.    99.  ]
 [ 99.    99.    99.   ...  99.    99.    99.  ]
 [ 99.     2.43   2.67 ...  99.    99.    99.  ]]
(array([15178, 24661,  7484, ..., 10346,  7718,  2332]), array([ 1, 61, 19, ..., 54, 20, 93]))


In [9]:
arr[idx[0][0], idx[1][0]]

3.74

In [10]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [11]:
n_latent_factors = 2

user_ratings = dframe.values
print(user_ratings.shape[0])
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

24982


In [12]:
latent_item_features

array([[0.826, 0.238],
       [0.938, 0.139],
       [0.82 , 0.954],
       [0.279, 0.588],
       [0.645, 0.376],
       [0.646, 0.358],
       [0.511, 0.227],
       [0.981, 0.018],
       [0.26 , 0.841],
       [0.865, 0.204],
       [0.187, 0.499],
       [0.624, 0.165],
       [0.701, 0.922],
       [0.694, 0.602],
       [0.09 , 0.125],
       [0.889, 0.556],
       [0.737, 0.635],
       [0.205, 0.126],
       [0.263, 0.15 ],
       [0.715, 0.666],
       [0.787, 0.222],
       [0.685, 0.354],
       [0.274, 0.008],
       [0.51 , 0.304],
       [0.192, 0.092],
       [0.175, 0.146],
       [0.531, 0.47 ],
       [0.033, 0.128],
       [0.633, 0.229],
       [0.032, 0.686],
       [0.916, 0.518],
       [0.28 , 0.462],
       [0.151, 0.21 ],
       [0.334, 0.741],
       [0.183, 0.762],
       [0.3  , 0.932],
       [0.653, 0.971],
       [0.267, 0.685],
       [0.816, 0.04 ],
       [0.417, 0.623],
       [0.36 , 0.706],
       [0.238, 0.694],
       [0.264, 0.677],
       [0.7

In [13]:
latent_user_preferences

array([[0.602, 0.615],
       [0.602, 0.373],
       [0.047, 0.529],
       ...,
       [0.413, 0.754],
       [0.97 , 0.282],
       [0.306, 0.434]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    #print(item_preference, user_preference)
    #print(user_preference.dot(item_preference))
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print (user_id, item_id)
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=300):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                #if not np.isnan(rating):
                if rating!=99:
                    #print (user_id, item_id, rating)
                    #err=0
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        #if (iteration % 100) == 0:
        print(mse)

In [15]:
#err = train(645, 54, 7.62)
#print(err)
sgd()

58.19935556460133
31.45092766281253
25.25947779728584
24.695998954756252
24.648498460956155
24.64040200502755
24.634071995217244
24.624960622593683
24.61064488996703
24.587733000485965
24.55085726894282
24.49155080542294
24.396764275197924
24.247188150550908
24.016185555558366
23.67137965858921
23.18244919104089
22.538115019864815
21.7678918512265
20.950263299738996
20.187472288013346
19.557799279271865
19.08644299451723
18.755075050080414
18.528752402578718
18.374883296700055
18.269375304962097
18.196024956964276
18.14426311861534
18.10720370687478
18.08031263641018
18.06056155474132
18.045897079749594
18.03490585225666
18.026600651341067
18.020282055379894
18.015447806971583
18.011732653333976
18.00886787804527
18.00665370389538
18.004940211322815
18.003613963087886
18.002588503681043
18.001797525562193
18.001189895679737
18.00072599669514
18.00037500896474
18.000112873578196
17.999920753772905
17.999783864644904
17.999690577461656
17.999631730367245
17.99960009533551
17.999589964175

KeyboardInterrupt: ignored

In [21]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[94.494,  2.807,  2.299, ...,  2.676,  1.896,  3.355],
       [48.902,  6.648,  7.122, ...,  7.487,  7.207,  8.301],
       [48.125,  2.555,  2.456, ...,  2.685,  2.315,  3.131],
       ...,
       [38.982, -0.583, -1.04 , ..., -0.941, -1.304, -0.816],
       [38.157, -0.304, -0.713, ..., -0.608, -0.957, -0.461],
       [72.918,  3.165,  2.914, ...,  3.238,  2.66 ,  3.851]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
#comparison_data.columns = pd.DataFrame.columns


In [26]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

0  ...                          100
0       (100.0, 94.49413633973043)  ...   (1.07, 3.3546518380748056)
1        (49.0, 48.90204299989754)  ...    (99.0, 8.300691925507875)
2        (48.0, 48.12470090003042)  ...     (99.0, 3.13088081846464)
3         (91.0, 91.4498791678156)  ...     (1.6, 4.054818166594594)
4       (100.0, 98.03273127258228)  ...   (-3.45, -5.32514749459483)
...                            ...  ...                          ...
24977  (100.0, 101.31066469277988)  ...    (7.43, 3.546718560176843)
24978    (91.0, 84.47980553713106)  ...   (8.45, 2.2324536212399386)
24979    (39.0, 38.98197353081132)  ...  (99.0, -0.8159122139312447)
24980    (37.0, 38.15682241745314)  ...  (99.0, -0.4614169989903101)
24981    (72.0, 72.91829986969758)  ...    (99.0, 3.850580062897365)

[24982 rows x 101 columns]